"""
Technical Summaries of ISO/IEC 5338 — AI System Life Cycle Processes (Clause 6)
Generated by Claude Opus 4.7 with the following prompt:

    I need technical summaries of ISO standard 5338 AI System Lifecycle Process.
    Please only focus on the document provided and do not add any further detail.
    Only exception is when a clause refers to "ISO/IEC/IEEE 15288:2023" and
    "ISO/IEC/IEEE 12207:2017". For these feel free to browse the web to add
    necessary context. Make sure the summaries are self-sufficient in terms of
    understanding.  Give the summary as a python dictionary where each key (process)
    maps to your summary. The summary should be longer than 3 sentences long and
    include helpful details such that a retriever system can query these documents
    reliably.

Each key is a process name; each value is a self-sufficient technical summary
suitable for retrieval/RAG indexing. Summaries focus exclusively on the
provided document, with brief context drawn from ISO/IEC/IEEE 15288:2023 and
ISO/IEC/IEEE 12207:2017 only where those parent standards are referenced
without further AI-specific elaboration.
"""

iso_5338_summaries = {

    # ============================================================
    # 6.1 AGREEMENT PROCESSES
    # ============================================================

    "Acquisition Process (6.1.1)": (
        "The acquisition process aims to obtain a product or service that meets the acquirer's "
        "requirements; in ISO/IEC 5338 the acquirer corresponds to the 'AI customer' role and the "
        "supplier to the 'AI producer'/'AI provider' roles defined in ISO/IEC 22989. The base "
        "outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 (6.1.1) and ISO/IEC/IEEE 12207:2017 "
        "(6.1.1) — which establish a common framework for acquiring systems and software through "
        "agreements between acquirers and suppliers — apply unchanged. The AI-specific particularity "
        "is that acquisition is extended beyond products and services to also include the acquisition "
        "of data for the AI data engineering process (see 6.4.8). This new acquisition activity "
        "introduces issues such as cost, dependencies, continuity, availability, and questions about "
        "data rights, rules, and legal requirements governing use of acquired data. Contracting and "
        "acceptance of training datasets is highlighted as particularly difficult to formalize, and "
        "acceptance can be followed by iterations of development or retraining performed in parallel "
        "with operations, so that the accepted dataset stays aligned with operational and business "
        "requirements."
    ),

    "Supply Process (6.1.2)": (
        "The supply process aims to provide an acquirer with a product or service that meets the "
        "requirements agreed in the agreement. The acquirer maps to the 'AI customer' role and the "
        "supplier to the 'AI producer' / 'AI provider' roles in ISO/IEC 22989. The outcomes, "
        "activities and tasks of ISO/IEC/IEEE 15288:2023 (6.1.2) and ISO/IEC/IEEE 12207:2017 (6.1.2) — "
        "covering tendering, contracting, delivery and acceptance of systems and software products/"
        "services — apply unchanged, and no additional AI-specific activities or tasks are defined. "
        "When negotiating and agreeing the supply, however, the supplier should consider four "
        "AI-specific particularities: (1) conducting a proof-of-concept to initiate AI system "
        "development before deployment; (2) provision, collection or acquisition of sufficient "
        "datasets for machine learning; (3) monitoring or intervention of the AI system during "
        "operation because its performance can vary depending on machine learning production data; "
        "and (4) analysis and improvement of the AI system to address any deviations from required "
        "performance."
    ),

    # ============================================================
    # 6.2 ORGANIZATIONAL PROJECT-ENABLING PROCESSES
    # ============================================================

    "Life Cycle Model Management Process (6.2.1)": (
        "The life cycle model management process defines, maintains and assures the availability of "
        "policies, life cycle processes, life cycle models and procedures used by the organization. "
        "ISO/IEC 5338 adds no AI-specific particularities to this process. The purpose, outcomes, "
        "activities and tasks given in ISO/IEC/IEEE 15288:2023 (6.2.1) and ISO/IEC/IEEE 12207:2017 "
        "(6.2.1) — which provide a common framework for describing system and software life cycles "
        "and their tailoring within an organization — apply directly. A note refers the reader to "
        "the typical AI system life cycle model described in clause 5.3 of ISO/IEC 5338 itself for "
        "AI-relevant context."
    ),

    "Infrastructure Management Process (6.2.2)": (
        "The infrastructure management process provides the enabling infrastructure (facilities, "
        "tools, communication and IT assets) that projects need to support organizational and project "
        "objectives across the life cycle. ISO/IEC 5338 introduces no AI-specific particularities for "
        "this process. The purpose, outcomes, activities and tasks given in ISO/IEC/IEEE 15288:2023 "
        "(6.2.2) and ISO/IEC/IEEE 12207:2017 (6.2.2) apply unchanged. The process is therefore "
        "identical to the parent standards' treatment, which positions it as one of the organizational "
        "project-enabling processes responsible for ensuring infrastructure is available, reliable "
        "and fit for purpose throughout the system life cycle."
    ),

    "Portfolio Management Process (6.2.3)": (
        "The portfolio management process initiates and sustains projects that meet the organization's "
        "strategic objectives, commits investment of funding and resources, sanctions authorities, and "
        "performs continued assessments to confirm that projects continue to justify investment or can "
        "be redirected. The outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 (6.2.3) and "
        "ISO/IEC/IEEE 12207:2017 (6.2.3) apply unchanged. Although no additional activities are added, "
        "organizations should consider AI-specific particularities: AI can offer new capabilities or "
        "business opportunities when defining and authorizing projects; resource allocation must "
        "account for the specific AI expertise required (see 6.2.4); especially when AI is new to an "
        "organization, multi-project aspects should be identified so that common AI system elements "
        "or platforms can be reused and knowledge exchanged between projects; and project evaluation "
        "should take AI-specific risks (see 6.3.4) and AI planning aspects (e.g. long ML training "
        "experimentation periods) into account."
    ),

    "Human Resource Management Process (6.2.4)": (
        "The human resource management process provides the organization with the necessary skilled, "
        "experienced and qualified personnel to perform life cycle processes and to maintain their "
        "competencies in line with business needs. The outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.2.4) and ISO/IEC/IEEE 12207:2017 (6.2.4) apply unchanged and no "
        "extra activities are introduced. AI-specific particularities focus on new stakeholder roles "
        "introduced by AI techniques: data scientists and data engineers act as AI developers in "
        "machine learning, and knowledge engineers act as AI developers in knowledge engineering. "
        "Organizations new to AI should review existing human resources and assess the appropriateness "
        "of their competencies. Detailed AI stakeholder roles (AI developers, AI providers, data "
        "providers, etc.) are catalogued in ISO/IEC 22989:2022, 5.17."
    ),

    "Quality Management Process (6.2.5)": (
        "The quality management process ensures that products, services and implementations meet both "
        "organizational/project quality objectives and customer requirements. The outcomes, activities "
        "and tasks of ISO/IEC/IEEE 15288:2023 (6.2.5) and ISO/IEC/IEEE 12207:2017 (6.2.5) apply "
        "without additions. Organizations should embed AI-specific particularities into their quality "
        "policies, objectives and procedures: quality assurance can take a more prominent role in "
        "organizations that develop, deploy and monitor AI systems, and continuous quality management "
        "supports systematic assessment of AI system performance throughout the life cycle, including "
        "after deployment. The clause emphasizes that quality is not a one-off check but an ongoing "
        "concern given the evolving behaviour of AI systems."
    ),

    "Knowledge Management Process (6.2.6)": (
        "The knowledge management process creates capabilities and assets — including knowledge, "
        "skills, knowledge assets and system elements — that enable the organization to reapply "
        "existing knowledge and exploit opportunities; knowledge used to create AI models is treated "
        "specifically in 6.4.7 and 6.4.9. The outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 "
        "(6.2.6) and ISO/IEC/IEEE 12207:2017 (6.2.6) apply unchanged. AI-specific particularities are: "
        "AI system elements such as datasets and data preparation scripts should be subject to "
        "knowledge management like any other system element; experimentation is central to AI "
        "implementation, so documenting experiments prevents repetition by the same or other "
        "stakeholders and yields lessons learned for improvement. Cross-references point to 6.2.4 for "
        "data-science expertise and to 6.4.8 for data lineage and data provenance."
    ),

    # ============================================================
    # 6.3 TECHNICAL MANAGEMENT PROCESSES
    # ============================================================

    "Project Planning Process (6.3.1)": (
        "The project planning process produces and coordinates effective and workable plans by "
        "determining the scope of management and technical activities, identifying outputs, tasks and "
        "deliverables, establishing schedules with achievement criteria and estimating required "
        "resources; planning is ongoing and revised throughout the project. The outcomes, activities "
        "and tasks of ISO/IEC/IEEE 15288:2023 (6.3.1) and ISO/IEC/IEEE 12207:2017 (6.3.1) apply "
        "unchanged. AI-specific particularities require flexibility in model creation because "
        "predictability is even harder than for traditional software: model creation can require AI "
        "data engineering (gathering, labelling, pre-processing — see 6.4.8), and ML-based systems "
        "involve iterations of experiments with different strategies/tactics to reach the desired "
        "model performance, while knowledge-engineering-based systems involve knowledge acquisition "
        "and elicitation. Project planning must also incorporate other AI particularities such as "
        "establishing continuous validation (see 6.4.14)."
    ),

    "Project Assessment and Control Process (6.3.2)": (
        "The project assessment and control process assesses whether plans are aligned and feasible, "
        "determines project, technical and process performance status, and directs execution so that "
        "performance follows plans, schedules and budgets and meets technical objectives. Periodic "
        "and event-driven evaluations enable management to redirect or replan when significant "
        "variances appear. The outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 (6.3.2) and "
        "ISO/IEC/IEEE 12207:2017 (6.3.2) apply unchanged with no extra AI-specific tasks. AI-specific "
        "particularities are that the 'plan for project assessment and control' activity can define "
        "intervals (set in the quality management process) for deciding whether to update the AI "
        "system or model, and that AI implementation is less predictable due to its iterative and "
        "experimental nature — for example, progress cannot be reliably measured by counting produced "
        "lines of code."
    ),

    "Decision Management Process (6.3.3)": (
        "The decision management process provides a structured analytical framework for objectively "
        "identifying, characterizing and evaluating alternatives at any point of the life cycle and "
        "selecting the most beneficial course of action. The outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.3.3) and ISO/IEC/IEEE 12207:2017 (6.3.3) apply unchanged. AI adds "
        "uncertainty and complexity, introducing new types of decisions including: retiring the AI "
        "system when its effective behaviour no longer meets requirements; 'refactoring' the AI "
        "system when ML training causes behaviour to drift from requirements (resetting the system "
        "and creating a new trained model); updating specifications and contracts between acquirer, "
        "user or supplier to reflect learned behaviour; and updating documentation to reflect learned "
        "behaviour while staying within requirements and contracts. The clause stresses defining how "
        "ML model quality is measured during 'analyse the decision information', and notes that AI "
        "decision points act as governance 'gates' as discussed in ISO/IEC 38507:2022, 5.3. Quality "
        "details for AI systems and ML models are in ISO/IEC 25059:2023 and ISO/IEC TS 25058."
    ),

    "Risk Management Process (6.3.4)": (
        "The risk management process is an ongoing process that systematically identifies, analyses, "
        "treats and monitors risks throughout the life cycle of a system, product or service, "
        "covering acquisition, development, maintenance and operation. The outcomes, activities and "
        "tasks of ISO/IEC/IEEE 15288:2023 (6.3.4) and ISO/IEC/IEEE 12207:2017 (6.3.4) apply unchanged, "
        "and detailed AI risk-management guidance is given in ISO/IEC 23894, whose objectives include "
        "fairness, privacy, reliability, transparency, explainability, accountability, availability, "
        "integrity and maintainability. Risk assessment must cover all AI-system risks and apply a "
        "risk-treatment plan with risk-management records; for safety- or security-critical AI, "
        "additional standards apply (e.g. ISO/IEC TR 5469 on functional safety, ISO 14971 for medical "
        "devices). The clause highlights autonomous on-going decision-making by AI systems where time "
        "constraints prevent human verification (e.g. self-driving): risks can be mitigated by "
        "operating boundaries, rules (e.g. do not open the trunk at high speed), or advanced reasoning "
        "with a world model, plus extensive test-case coverage and inclusion of risky cases in "
        "training data, and human retrospective analysis. Safety-related AI systems shall maintain an "
        "audit trail (data provenance, source validation, risk analysis/mitigation, decisions), and "
        "development shall include an audit strategy — e.g. storing past decisions with references to "
        "the model used and how that model was created, plus the rationale for key development "
        "decisions. Stakeholder input (per 6.4.2) must inform risk and opportunity identification."
    ),

    "Configuration Management Process (6.3.5)": (
        "Configuration management (CM) manages and controls system elements and configurations across "
        "the life cycle and ensures consistency between a product and its configuration definition "
        "(see ISO 10007). The outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 (6.3.5) and "
        "ISO/IEC/IEEE 12207:2017 (6.3.5) apply, with one added activity: an automated process "
        "for model rollback can be used to quickly resolve suboptimal model performance. AI systems "
        "introduce additional artefacts requiring CM: the data representing the model (rules, weights, "
        "parameters), AI documentation, data and metadata; for ML it is beneficial to place the model "
        "and its training data jointly under CM for traceability (auditing, compliance, reproducing "
        "experiments). AI artefacts — especially datasets — are large and typically stored separately "
        "from code, which can force compromises such as shorter version retention. A typical "
        "application is rollback to a previous runtime model when a new one shows quality issues. "
        "Data used to build and test the model should be under CM, especially where AI performance is "
        "continuously monitored and maintained (see 6.4.14–6.4.16). Conventional version management "
        "is no longer sufficient because development/logistics versions of configuration items do not "
        "guarantee operational behaviour, and multiple deployed instances of the same configuration "
        "can behave differently. Design and development should also include AI-specific source code "
        "management controls (e.g. for AI data engineering and model training)."
    ),

    "Information Management Process (6.3.6)": (
        "The information management process generates, obtains, confirms, transforms, retains, "
        "retrieves, disseminates and disposes of unambiguous, complete, verifiable, consistent, "
        "modifiable, traceable and presentable information for designated stakeholders. The "
        "information covered includes technical, project, organizational, agreement and user "
        "information typically derived from data records of the organization, system, process or "
        "project. The outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 (6.3.6) and "
        "ISO/IEC/IEEE 12207:2017 (6.3.6) apply without additions. The AI-specific particularity is "
        "that AI systems are very data-intensive, involving datasets for testing and (for ML) for "
        "training, and these datasets are part of the information that must be managed (cross-"
        "reference to 6.4.8 on AI data engineering)."
    ),

    "Measurement Process (6.3.7)": (
        "The measurement process collects, analyses and reports data relating to products and "
        "processes to support effective management; the purpose, outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.3.7) and ISO/IEC/IEEE 12207:2017 (6.3.7) apply unchanged. In "
        "addition, processes for AI-specific measurements shall be considered when the AI system is "
        "safety-related (e.g. probability of erroneous output) and are recommended for other AI "
        "systems too. Specifically, drift in AI models — both due to environment changes and due to "
        "autonomous changes in the model itself — should be measured so that corrections can be made."
    ),

    "Quality Assurance Process (6.3.8)": (
        "Quality assurance (QA) ensures the effective application of the organization's quality "
        "management process to the project, providing confidence that quality requirements are met "
        "through proactive analysis of life cycle processes and outputs. The outcomes, activities and "
        "tasks of ISO/IEC/IEEE 15288:2023 (6.3.8) and ISO/IEC/IEEE 12207:2017 (6.3.8) apply unchanged, "
        "but QA can take a more prominent role for AI systems. AI systems can evolve over time (e.g. "
        "continuous-learning systems), demanding close quality monitoring and assurance to detect "
        "deteriorating effectiveness from low-quality input data, concept drift or data drift. In QA, "
        "both products and processes are evaluated; for AI, ML algorithms and data are also "
        "considered products to be evaluated, and AI-specific quality characteristics (transparency, "
        "fairness, accountability, robustness — see ISO/IEC 25059 and ISO/IEC TS 25058) must be "
        "included. Processes evaluated should cover proof-of-concept analysis, requirement and risk "
        "analysis for adequate problem-domain coverage, iterative ML tasks, and procedures for "
        "creating training data (collection, selection, generation, validation, modification or "
        "addition). QA must monitor low-quality input data, data drift and concept drift, and the "
        "level of QA effort should match environmental complexity, autonomy level, AI output impact, "
        "regulatory requirements and quality-system requirements; continuous-learning systems require "
        "appropriate revalidation activities. Cross-references: 6.2.5, 6.4.11, 6.4.13, 6.4.14, and "
        "data quality analysis in 6.4.8."
    ),

    # ============================================================
    # 6.4 TECHNICAL PROCESSES
    # ============================================================

    "Business or Mission Analysis Process (6.4.1)": (
        "The business or mission analysis process defines the business/mission problem or opportunity, "
        "characterizes the solution space and determines candidate solution classes that could address "
        "the problem or exploit the opportunity. The outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.4.1) and ISO/IEC/IEEE 12207:2017 (6.4.1) apply unchanged with no "
        "added activities. AI-specific risks (see 6.3.4) can influence or even prohibit the realization "
        "of certain business goals: when implementing 'define the problem or opportunity space', "
        "organizations shall consider that privacy regulations can prevent personal data being used "
        "for a use case different from the original collection intent, and where decisions can affect "
        "individuals negatively, legal requirements can demand explanations of which data were used "
        "and how. Other illustrative risks include the degree of data accessibility and data quality."
    ),

    "Stakeholder Needs and Requirements Definition Process (6.4.2)": (
        "This process captures stakeholder requirements so the system can deliver the capabilities "
        "needed by users and other stakeholders in a defined environment, identifying stakeholders "
        "and stakeholder classes throughout the AI system life cycle and transforming their needs "
        "into a common set of requirements that express intended interactions with the operational "
        "environment. The outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 (6.4.2) and "
        "ISO/IEC/IEEE 12207:2017 (6.4.2) apply unchanged. Because AI is inductive in nature, the task "
        "of obtaining explicit agreement on stakeholder requirements — including critical performance "
        "measures used as targets for assessing technical achievement — is crucial, and biases from "
        "narrow stakeholder views must be considered. Specific AI stakeholder types to consider "
        "include providers of AI platforms/products/services, AI developers, customers and users, "
        "partners involved in system integration/data provision/auditing, regulatory and policy-making "
        "authorities, data subjects and others impacted by the AI system; values elicited can shape "
        "user interfaces, documentation and use cases and may be refined into system requirements "
        "using regulation, human rights, social responsibility and environmental frameworks. "
        "ISO/IEC 22989:2022 (5.17) lists AI stakeholder types in detail, and ISO/IEC 25059 / "
        "ISO/IEC TS 25058 provide quality models useful for eliciting non-functional requirements."
    ),

    "System Requirements Definition Process (6.4.3)": (
        "This process transforms stakeholder requirements into a technical view of a solution that "
        "still meets users' operational needs, factoring in outputs from risk management and "
        "governance processes, and produces a set of measurable system requirements describing the "
        "system's characteristics, attributes, functional and performance requirements from the "
        "supplier's perspective, without implying a specific implementation. The outcomes, activities "
        "and tasks of ISO/IEC/IEEE 15288:2023 (6.4.3) and ISO/IEC/IEEE 12207:2017 (6.4.3) apply "
        "unchanged. AI systems require additional considerations: desired model performance "
        "(precision, accuracy and the input range over which the model should perform — e.g. "
        "distinguishing cats and dogs in 90% of daytime photos showing the entire animal); level of "
        "autonomy (including human-in-the-loop and what decisions humans can take such as adjusting "
        "performance thresholds); how to handle unexpected behaviour (e.g. additional deterministic "
        "safety rules); system performance such as execution time; transparency and explainability "
        "(legally required in some cases, e.g. denied credit applications, ranging from detailed to "
        "high-level explanations of data/algorithm used); informing individuals when they interact "
        "with an AI system as required by law; continuous validation requirements (see 6.4.14); "
        "fairness requirements with defined fairness metrics and interpretable features so fairness "
        "can be verified; privacy requirements when personal data is used, including informing "
        "individuals, providing control and protection, and possibly using differentially private "
        "algorithms; and security requirements addressing the AI-specific attack surface — securing "
        "training/test data against poisoning attacks, protecting against input manipulation (e.g. "
        "spam classified as not-spam), model inversion attacks (deconstructing sensitive training "
        "data) and model theft."
    ),

    "System Architecture Definition Process (6.4.4)": (
        "The system architecture definition process establishes the architecture of a system in "
        "terms of elements, relationships, interfaces and rationale, ensuring alignment with the "
        "system requirements. In ISO/IEC/IEEE 12207:2017 (6.4.4) it is named 'architecture "
        "definition process'. ISO/IEC 5338 specifies that the purpose, outcomes, activities and "
        "tasks given in ISO/IEC/IEEE 15288:2023 (6.4.4) and ISO/IEC/IEEE 12207:2017 (6.4.4) apply "
        "unchanged. No AI-specific particularities, additions, modifications or new tasks are "
        "introduced. AI-related architectural considerations therefore need to be handled through "
        "the parent standards' generic architecture activities, informed by the AI-specific risk "
        "and requirement clauses elsewhere in the document."
    ),

    "Design Definition Process (6.4.5)": (
        "The design definition process provides sufficient detailed data and information about a "
        "system and its elements to enable its implementation, consistent with the architectural "
        "entities. ISO/IEC 5338 states that the purpose, outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.4.5) and ISO/IEC/IEEE 12207:2017 (6.4.5) apply unchanged. No "
        "AI-specific particularities, additions or modifications are introduced. Any AI-specific "
        "design implications are handled implicitly through the requirement, risk and implementation "
        "clauses, leaving the design process formally identical to the parent standards."
    ),

    "System Analysis Process (6.4.6)": (
        "The system analysis process produces analytical results from technical investigations "
        "(performance, cost, risk, effectiveness, etc.) to provide a rigorous basis for technical "
        "understanding and decision-making. ISO/IEC 5338 specifies that the purpose, outcomes, "
        "activities and tasks of ISO/IEC/IEEE 15288:2023 (6.4.6) and ISO/IEC/IEEE 12207:2017 (6.4.6) "
        "apply unchanged, and introduces no AI-specific particularities. AI-related analytical needs "
        "are therefore expected to be handled through the generic system-analysis activities of the "
        "parent standards, supported by other AI-specific clauses (e.g. risk management in 6.3.4 and "
        "decision management in 6.3.3)."
    ),

    "Knowledge Acquisition Process (6.4.7)": (
        "The knowledge acquisition process — defined as a new AI-specific process by ISO/IEC 5338 — "
        "provides the knowledge needed to create AI models; for ML-based AI systems this knowledge "
        "guides data selection, data preparation and model engineering, while for knowledge-based AI "
        "systems the knowledge must be coded explicitly into the model. Knowledge can come from "
        "research and/or subject-matter experts, and data analysis (6.4.8) can contribute. Outcomes "
        "are: (a) knowledge needed to create AI models is identified; (b) gathered knowledge is "
        "stored; (c) traceability of knowledge acquisition is established. The activities and tasks "
        "are: (a) define scope and criteria of the knowledge (domain, aspect, recency); (b) seek and "
        "gather knowledge sources from publications, data or experts; (c) perform knowledge "
        "acquisition by studying publications, analysing data, interviewing/observing experts — for "
        "knowledge engineering, the extracted knowledge must be formalized so algorithms can use it "
        "(part of the implementation process, 6.4.9); (d) gather domain/problem knowledge through "
        "study, interviews, knowledge elicitation, data analysis, documented sources or stakeholder "
        "involvement; (e) manage the knowledge-acquisition results. Notes refer to ISO/IEC 5392 for "
        "knowledge engineering roles, components and vocabulary, and indicate that knowledge can be "
        "shared between projects via repositories and registries, with reuse of proven patterns "
        "considered during knowledge collection (linked to model development in 6.4.9.3)."
    ),

    "AI Data Engineering Process (6.4.8)": (
        "The AI data engineering process — a new AI-specific process introduced by ISO/IEC 5338 — "
        "ensures that data can be used to create and verify AI models; data is central to ML model "
        "training and secondary (knowledge-engineering supporting) for heuristic models (6.4.9). "
        "Outcomes include: required data and datasets are identified, sampled and obtained; training "
        "and (where needed) validation data are prepared, formatted and made available to ML models; "
        "test data are prepared (6.4.11); data for manual analysis to support data and model "
        "engineering are prepared; automated ETL processes are identified; recording and use of "
        "personal information complies with applicable laws; artefacts (e.g. metadata) for "
        "traceability, documentation, maintenance and configuration management are prepared; data is "
        "retired in a timely manner; and multi-modal data (voice, images, sensors) is managed. "
        "Activities and tasks are: (a) acquire or select data — gathering structured data, text, "
        "sound, image and other sensory data from existing stores, recordings or orchestrated "
        "processes; the famous 'wolves recognized by snow' example illustrates that test data should "
        "come from a different source/process than training data to test generalization, and data "
        "acquisition should be ongoing where input/output relations change over time (e.g. land "
        "prices), with outdated data retired; (b) conduct data labelling — typically manual, "
        "controlled to prevent bias/noise, performed by domain-competent and tool-trained people, "
        "with review/correction depending on application risk, and proper validation of labelling "
        "tools; (c) analyse and explore data for understanding of domain, problem and data issues — "
        "informing whether more data or different processing is needed (ML) or further shaping of "
        "knowledge (knowledge engineering); (d) analyse data quality — assess completeness, balance, "
        "edge cases, bias (verifying balance against protected social attributes; removing those "
        "attributes alone is often insufficient because of proxy variables) and the risk of data "
        "poisoning; quality checks should be automated and ongoing (see ISO/IEC 5259 series and "
        "ISO/IEC TR 24027); (e) document data lineage and data provenance — lineage records origin, "
        "processing and movement over time enabling forward/backward error tracing, while provenance "
        "documents inputs, entities, systems and processes; (f) clean, merge and prepare data — "
        "extraction, merging, cleaning, filtering, correcting, augmenting, conversion, encoding and "
        "missing-value handling, including feature engineering (selecting/characterizing/optimizing "
        "features), filtering of unwanted/excessive/biased/privacy-sensitive/protected data, data "
        "augmentation (e.g. image rotation), conversion/encoding to satisfy model input criteria, "
        "and possibly generative AI methods to auto-generate metadata; preparation is often ad hoc "
        "but should aim for reusable automation with automated testing of preparation code; "
        "(g) protect sensitive data — AI data engineering increases the attack surface, so data "
        "stores and pipelines need careful handling and privacy-preserving techniques, especially "
        "when combining personal data from different sources."
    ),

    "Implementation Process (6.4.9)": (
        "The implementation process realizes a specified system element by transforming requirements, "
        "architecture, design and interfaces into actions that build a system element using the "
        "selected implementation technology. Outcomes/activities/tasks of ISO/IEC/IEEE 15288:2023 "
        "(6.4.7) and ISO/IEC/IEEE 12207:2017 (6.4.7) apply, plus AI model engineering outcomes — "
        "(a) a working AI model is produced and (b) modelling-process documentation is produced — "
        "and additional activities. For ML-based AI systems: (a) algorithm selection, taking into "
        "account the model task type (clustering, time-series prediction, classification) and the "
        "best technique (which can be determined by experimentation), balancing interpretability/"
        "explainability against performance, since interpretable models build trust, transparency, "
        "support accountability and help developers understand the problem and data; (b) model "
        "training, running the algorithm iteratively over training data to learn an internal "
        "representation (e.g. neural network weights) — for supervised learning, estimating the "
        "function that maps input to desired output while preventing overfitting (good on training "
        "data, poor on production data); (c) model tuning, using optimization techniques on "
        "validation data to find the best hyperparameters. For knowledge-engineering-based AI "
        "systems: (d) knowledge programming — formalizing acquired knowledge (from 6.4.7) into a "
        "heuristic model with explicit procedural computations or implicit declarative "
        "rules/probabilities, and defining a combined cloud/edge architecture to manage emerging "
        "behaviour, especially in industrial applications. AI-specific particularities note that AI "
        "systems are traditional software systems that apply one or more AI models with new elements; "
        "an actively maintained backlog supports cross-disciplinary coordination; ML model "
        "engineering iteratively trains, tunes and tests the model with separate datasets (see "
        "6.4.11); AutoML can automate parts of these processes to reduce reliance on expert "
        "experience and increase efficiency, including parallelizing experimentation across experts "
        "and computing resources, though training can need substantial compute and time; transfer "
        "learning starts from an existing trained model to gain efficiency on a related use case; "
        "existing software frameworks supply built-in models and tooling for data processing, "
        "training, testing and orchestration; for knowledge engineering, model engineering "
        "specifies knowledge declaratively or procedurally based on knowledge from experts "
        "(elicitation) or data analysis (6.4.8)."
    ),

    "Integration Process (6.4.10)": (
        "The integration process combines system elements to form complete or partial implementations "
        "of the system, ensuring that the integrated elements work together as specified. ISO/IEC 5338 "
        "states that the purpose, outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 (6.4.8) "
        "and ISO/IEC/IEEE 12207:2017 (6.4.8) apply unchanged. No AI-specific particularities are "
        "added for this process. Integration of AI components into the broader system therefore "
        "follows the parent standards' generic guidance, informed by the architecture, design and "
        "implementation activities elsewhere in the document."
    ),

    "Verification Process (6.4.11)": (
        "The verification process provides objective evidence that a system or system element fulfils "
        "its specified requirements and characteristics, identifying anomalies (errors, defects, "
        "faults) in any information item, implemented system element or life cycle process and "
        "providing information for resolution. The outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.4.9) and ISO/IEC/IEEE 12207:2017 (6.4.9) apply with no extra "
        "activities. The first AI-specific particularity is verification through behaviour: AI models "
        "are constructed to approximate desired behaviour rather than be programmed exactly, so they "
        "must be verified statistically using verification datasets containing inputs and desired "
        "outputs, applying statistical techniques to measure correctness and robustness (see 6.4.3). "
        "Verification datasets can be a separate subset of the same source as the training data or "
        "from a different source — the latter better tests generalization. Two dataset types are "
        "distinguished: validation data (to select among candidate models) and test data (to "
        "determine whether the final model performs and generalizes adequately). The second "
        "AI-specific particularity is verification through review: code review is suitable for source "
        "code specifically written for the AI system, including knowledge encoded in heuristic "
        "systems, but for ML models the algorithm source code in libraries/frameworks cannot be "
        "reviewed and the model's behaviour is determined by parameter values whose correctness is "
        "very hard to assess because the algorithm follows automatically optimized steps rather than "
        "human-implemented logic. Organizations should ensure AI-related source code is included in "
        "regular code-quality reviews (maintainability, testability, reusability) — e.g. peer "
        "reviewing training scripts and unit-testing data preparation code. See 6.4.14 for "
        "continuous validation."
    ),

    "Transition Process (6.4.12)": (
        "The transition process establishes the capability for a system to deliver the services "
        "specified by stakeholder requirements in the operational environment, moving the verified "
        "system in an orderly, planned manner into operational status. It installs the verified "
        "system together with enabling systems (planning, support, training, user training systems) "
        "defined in agreements, and is applied at each level and stage to satisfy stage-exit "
        "criteria, including storage, handling and shipping. Outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.4.10) and ISO/IEC/IEEE 12207:2017 (6.4.10) apply unchanged. "
        "AI-specific particularities are that there is often a difference between the AI system that "
        "runs the model and the model itself (a configuration or set of parameters such as neural "
        "network weights), and AI models can be deployed in a different format from how they were "
        "developed because of operational requirements. The organization should support model "
        "updates (retraining or knowledge engineering) and execute continuous monitoring of "
        "AI-system metrics. Deployed AI systems can exhibit unexpected behaviour due to bias or "
        "unexpected input, making monitoring important and procedures more extensive than for "
        "traditional systems. Possible timing of a model update is influenced by changes in "
        "operational processes, observed data drift (ISO/IEC 23053), observed concept drift "
        "(deterioration in precision, ISO/IEC 23053) and the time elapsed since the last model "
        "update or creation. For AI systems that improve over time, the organization should support "
        "'quality in use' through quality management — for example, by monitoring usage trends."
    ),

    "Validation Process (6.4.13)": (
        "The validation process provides objective evidence that the system, when in use, fulfils its "
        "business or mission objectives and stakeholder requirements and achieves its intended use in "
        "its intended operational environment, with confidence ratified by stakeholders and anomalies "
        "fed back to the appropriate technical process for resolution. The outcomes, activities and "
        "tasks of ISO/IEC/IEEE 15288:2023 (6.4.11) and ISO/IEC/IEEE 12207:2017 (6.4.11) apply with no "
        "additional activities. AI-specific particularities are: organizations can perform "
        "proof-of-concept projects so that validation also covers the value and risks of AI itself "
        "for the organization; the organization should support model updates (retraining or "
        "knowledge engineering) and continuous monitoring of established metrics; performance can be "
        "affected after deployment, so monitoring metrics should be designed accordingly; AI systems "
        "can exhibit unexpected behaviour (bias, unexpected input), making monitoring more extensive "
        "than for traditional systems. Possible timing of a model update is influenced by changes in "
        "operational processes, observed data drift (ISO/IEC 23053), observed concept drift (ISO/IEC "
        "23053) and time since the last model update/creation. For AI systems that improve over time, "
        "quality in use should be supported through quality management — e.g. by monitoring usage "
        "trends."
    ),

    "Continuous Validation Process (6.4.14)": (
        "The continuous validation process — a new AI-specific process introduced by ISO/IEC 5338 — "
        "monitors that AI models keep performing satisfactorily and demonstrates their performance "
        "over time, recognising that desired behaviour and production data can change. It uses test "
        "data to detect deviations of input data (data drift) and deviations from desired output "
        "(concept drift), and serves as an extension of the quality assurance process (6.3.8). "
        "Substantial deviations may require ML retraining or continuous learning as part of "
        "maintenance (6.4.16) and can also indicate other issues such as data-quality problems or "
        "system malfunction; for automated continuous learning without human interaction, an "
        "automated rollback process at defined thresholds should prevent undesired model changes. "
        "Outcomes are: (a) validation results recorded in a validation log and (b) a decision can be "
        "made to perform maintenance (retraining) on the AI model. Activities and tasks: "
        "(a) monitor for data drift by checking model input data against training distribution; "
        "(b) monitor for concept drift by measuring model performance on updated test data or "
        "detecting anomalies in output values or output-value distribution (e.g. comparing recent to "
        "previous output); (c) monitor any other requirements expected to change over time (see "
        "6.4.3) such as execution time, transparency and fairness; (d) decide whether to perform "
        "maintenance on the AI model in case of deviations; (e) apply guard rails — e.g. boundaries "
        "on output data or defaulting to an alternative safe model — when defined; (f) determine the "
        "frequency at which validation should occur."
    ),

    "Operation Process (6.4.15)": (
        "The operation process uses the system to deliver its services, allocating personnel to "
        "operate the system, monitoring services and operator-system performance, and identifying "
        "and analysing operational anomalies relative to agreements, stakeholder requirements and "
        "organizational constraints. The outcomes, activities and tasks of ISO/IEC/IEEE 15288:2023 "
        "(6.4.12) and ISO/IEC/IEEE 12207:2017 (6.4.12) apply with no additional activities. The "
        "first AI-specific particularity concerns computer resource and power usage: AI systems can "
        "consume considerable compute and memory — particularly ML training, sometimes using GPUs "
        "for parallel processing — leading to extra cost and carbon footprint that influence "
        "decisions about training frequency, algorithm choice and whether to use ML at all; models "
        "can be deployed in batch or continuous mode, with continuous mode imposing stricter "
        "performance efficiency requirements. The second particularity is to consider production "
        "data early in the life cycle, including availability, fit for intended behaviour, diversity "
        "of features, and consistency between training/test/production data, leveraging independent "
        "datasets where applicable, and translating these into functional/technical specifications, "
        "user guides or production-data metrics. The third particularity is model deployment: models "
        "can be deployed separately from the rest of the system because of specific runtime hardware/"
        "software requirements, especially when models are replaced more often (e.g. after "
        "retraining); runtime models may differ from development models because development "
        "environments are not compatible with runtime constraints (e.g. embedded systems versus "
        "simulated PC environments). The organization should support model updates and continuous "
        "monitoring; deployed AI systems can show unexpected behaviour from bias or unexpected "
        "input, requiring more extensive monitoring than traditional systems. Possible timing of a "
        "model update is influenced by changes in operational processes, observed data drift "
        "(ISO/IEC 23053), observed concept drift (ISO/IEC 23053) and time since last model creation/"
        "update. For self-improving AI, quality in use should be supported through quality "
        "management — e.g. monitoring usage trends; all incidents including system failures and data "
        "errors should be reported and assessed."
    ),

    "Maintenance Process (6.4.16)": (
        "The maintenance process sustains the system's capability to provide service by monitoring "
        "delivery, recording incidents for analysis, taking corrective, adaptive, perfective and "
        "preventive actions (see ISO/IEC/IEEE 14764), and confirming restored capability. The "
        "outcomes, activities or tasks of ISO/IEC/IEEE 15288:2023 (6.4.13) and ISO/IEC/IEEE 12207:2017 "
        "(6.4.13) apply with these additional activities: continuous training of the AI model — "
        "rather than occasional retraining, the model evolves constantly as it is trained with "
        "production data to accommodate changing behaviour over time, implemented either as regular "
        "automated retraining or as incremental training; the organization assesses how AI-system "
        "performance can be affected after deployment and designs appropriate monitoring metrics for "
        "continuous validation (6.4.14); and the organization aims to support model updates "
        "(retraining or knowledge engineering) to maintain model performance, monitored by the "
        "continuous validation process. AI-specific particularities: maintenance is extended to "
        "include continuous learning; like traditional software, AI maintenance can include earlier "
        "process activities — especially implementation — and design/implementation can evolve "
        "constantly; models can need retraining or other updates (model engineering, 6.4.9), new "
        "training data can be collected, data preparation can change (6.4.8) and test data can need "
        "updating (6.4.11). Continuous training can replace occasional retraining. Monitoring AI is "
        "different from traditional monitoring, hence the dedicated continuous validation process "
        "(6.4.14). Deployed AI systems can show unexpected behaviour from bias or unexpected input, "
        "so monitoring procedures are more extensive than for traditional systems. Update timing is "
        "influenced by operational-process changes, data drift (ISO/IEC 23053), concept drift "
        "(ISO/IEC 23053) and time since last update/creation. For self-improving AI, quality in use "
        "should be supported through quality management — e.g. monitoring usage trends. If a "
        "deployed model performs suboptimally because of production-data changes or detected skew, "
        "it can be rolled back to an earlier better-performing version, repaired or made more robust, "
        "so an automated rollback process is beneficial. Maintenance can be complex because AI "
        "behaviour can be unstable and not always explainable even with engineering documents, and "
        "configuration-item versions do not always reflect actual AI-system behaviour."
    ),

    "Disposal Process (6.4.17)": (
        "The disposal process ends the existence of a system element or system for a specified "
        "intended use, appropriately handles replaced or retired elements, and addresses identified "
        "critical disposal needs. Such needs may arise from agreements, organizational policy, or "
        "environmental, legal, safety or security aspects. The outcomes, activities and tasks of "
        "ISO/IEC/IEEE 15288:2023 (6.4.14) and ISO/IEC/IEEE 12207:2017 (6.4.14) apply unchanged. The "
        "AI-specific particularity is that disposal is extended beyond systems to include the "
        "disposal of data: any data involved with the AI system can require thorough disposal "
        "because of security or privacy risks. The data disposal process must take applicable "
        "retention requirements into account, as described in ISO/IEC 38507."
    ),
}

if __name__ == "__main__":
    for process, summary in iso_5338_summaries.items():
        print(f"\n{'='*80}")
        print(process)
        print(f"{'='*80}")
        print(summary)
