_wandb:
    value:
        cli_version: 0.26.1
        e:
            qbpb6j39nf2b6lhz7tmgeevgu4tdqn9q:
                codePath: IS584_Assignment3.ipynb
                codePathLocal: IS584_Assignment3.ipynb
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1013309239296"
                        used: "520699924480"
                executable: C:\Users\ozgu.ozkan\Desktop\IS584_A3\IS584_Assign3\Scripts\python.exe
                git:
                    commit: 5b7eb544ce6c236f8e731eb97424a5115b47122d
                    remote: https://github.com/ozguozkan/nlp_assign3.git
                gpu: NVIDIA GeForce RTX 4090 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 9728
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4090 Laptop GPU
                      uuid: GPU-1f994685-d36f-c01d-1c9b-dbfb8e368ba3
                host: BTS0225
                memory:
                    total: "34029162496"
                os: Windows-11-10.0.26100-SP0
                program: IS584_Assignment3.ipynb
                python: CPython 3.13.7
                root: C:\Users\ozgu.ozkan\Desktop\IS584_A3
                startedAt: "2026-05-14T10:52:41.727461Z"
                writerId: qbpb6j39nf2b6lhz7tmgeevgu4tdqn9q
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.26.1
            "6": 5.8.0
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.26.1
            "13": windows-amd64
alpha:
    value: 0.2
model:
    value: all-MiniLM-L6-v2
